### ISSUE TITLE
Establish and measure org-wide coding standards

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/coding-standards#1]
From many, many ... many compared `phpcs` files, especially interesting are:

- [wearerequired/coding-standards: 💻 required coding standards for PHP, JavaScript and CSS.](https://github.com/wearerequired/coding-standards)
- [humanmade/coding-standards: Human Made coding standards for modern code](https://github.com/humanmade/coding-standards)
- [WordPress/pattern-directory: The WordPress Block Pattern Directory](https://github.com/WordPress/pattern-directory)
```[tasklist]
### Tasks
- [x] Fork or create an own set of rules
- [x] Integrate CS validation within a required status check
```

**Comment by carstingaxion** [comment]
>Fork or create an own set of rules

- [x] https://github.com/figuren-theater/coding-standards

>Integrate CS validation within a required status check

- [x] https://github.com/figuren-theater/.github/blob/main/.github/ISSUE_TEMPLATE/quality-standards.md
